### ISSUE TITLE
how the hell do i use this

### ISSUE THREAD

**Issue by zuqwz** [Blank-c/BlankOBF#14]
`c:\Users\zuqwz>python BlankOBF.py -o D: main.py

Traceback (most recent call last):
  File "c:\Users\zuqwz\BlankOBF.py", line 144, in <module>
    BlankOBF(code, args.path)
  File "c:\Users\zuqwz\BlankOBF.py", line 24, in __init__
    self.finalize()
  File "c:\Users\zuqwz\BlankOBF.py", line 121, in finalize
    with open(self.outpath, "w") as e:
         ^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'D:'`

executed the command on cmd with admin

**Comment by dfgszdgzsdgszdgzsdgzsadgzsadgszgd** [comment]
python BlankOBF.py "main.py"
