### ISSUE TITLE
error

### ISSUE THREAD

**Issue by DemoTrojan** [Blank-c/BlankOBF#21]
Traceback (most recent call last):
  File "/home/tona/BlankOBFv2.py", line 360, in <module>
    main()
  File "/home/tona/BlankOBFv2.py", line 351, in main
    obfuscated_code = obfuscator.obfuscate()
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tona/BlankOBFv2.py", line 28, in obfuscate
    self._save_imports()
  File "/home/tona/BlankOBFv2.py", line 55, in _save_imports
    self._imports.sort(reverse= True)
TypeError: '<' not supported between instances of 'NoneType' and 'str'

**Comment by Blank-c** [comment]
Check the latest commit for the fix
